### ISSUE TITLE
[docs] sort documentation pipeline throughout stack

### ISSUE THREAD

**Issue by zramsay** [monax/eris#1093]
**Problem:** consistency in how the documentation is organized/published/presented is lacking

**Solution:** harmonize across remaining (and decreasing) repos along with monax.io

**Comment by compleatang** [comment]
Proposal to move both solidity tuts and getting started tut into either this repo or a dedicated tutorials repo for open source contributions....

**Comment by zramsay** [comment]
added as #1163

**Comment by zramsay** [comment]
basically handled in #1274
